Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BrainBox.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public IActionResult OnPostRedirectToPage()
        {
            return RedirectToPage("/Quiz/QuizSelection"); // Change "AnotherPage" to the page you want to redirect to
        }
        public void OnGet()
        {

        }
    }
}

Pages/Quiz/QuizMatch.cshtml.cs
using BrainBox.Models.Dtos;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Text.Json;

namespace BrainBox.Pages.Quiz
{
    public class QuizMatchModel : PageModel
    {
        public string Category { get; set; } = string.Empty;
        public string Type { get; set; } = string.Empty;
        public string Difficulty { get; set; } = string.Empty;
        public string NoOfQuestions { get; set; } = string.Empty;

        public async Task OnGet(string category, string type, string difficulty, string noOfQuestions)
        {
            Category = category;
            Type = type;
            Difficulty = difficulty;
            NoOfQuestions = noOfQuestions;

            HttpClient httpClient = new HttpClient();
            var quizUri = GetQuizUrl(category, type, difficulty, noOfQuestions);
            var response = await httpClient.GetAsync(quizUri);

            if (response != null && response.IsSuccessStatusCode)
            {
                var jsonString = await response.Content.ReadAsStringAsync();
                var quizResponse = JsonSerializer.Deserialize<QuizResponseDto>(jsonString, new JsonSerializerOptions { PropertyNameCaseInsensitive = false });
                if (quizResponse.ResponseCode != 0)
                {
                    response = await httpClient.GetAsync($"https://opentdb.com/api.php?amount={noOfQuestions}&category={category}");
                    if (response != null && response.IsSuccessStatusCode)
                    {
                        jsonString = await response.Content.ReadAsStringAsync();
                        quizResponse = JsonSerializer.Deserialize<QuizResponseDto>(jsonString, new JsonSerializerOptions { PropertyNameCaseInsensitive = false });
                    }
                }

                if (quizResponse != null)
                {
                    Console.WriteLine($"Response Code: {quizResponse.ResponseCode}");

                    foreach (var question in quizResponse.Results)
                    {
                        Console.WriteLine($"Category: {question.Category}");
                        Console.WriteLine($"Question: {question.Description}");
                        Console.WriteLine($"Correct Answer: {question.CorrectAnswer}");
                        Console.WriteLine($"Incorrect Answers: {string.Join(", ", question.IncorrectAnswers)}");
                        Console.WriteLine();
                    }
                }
            }
            else
            {
                Console.WriteLine("Failed to fetch data.");
            }
        }

        private string GetQuizUrl(string category, string type, string difficulty, string noOfQuestions)
        {
            var baseUrl = $"https://opentdb.com/api.php?amount={noOfQuestions}";
            if(category.ToLower().Trim() != "any")
            {
                baseUrl += $"&category={category}";
            }

            if (difficulty.ToLower().Trim() != "any")
            {
                baseUrl += $"&difficulty={difficulty}";
            }

            if (type.ToLower().Trim() != "any")
            {
                baseUrl += $"&type={type}";
            }

            return baseUrl ;
        }
    }
}

Pages/Quiz/QuizSelection.cshtml.cs
using BrainBox.Models.Dtos;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BrainBox.Pages.Quiz
{
    [Authorize]
    public class QuizSelectionModel : PageModel
    {
        [BindProperty]
        public UserSelectionDto UserSelection { get; set; }
        public IActionResult OnPost()
        {
            // Redirect to the next page with the form data as a query string
            return RedirectToPage("/Quiz/QuizMatch", new { category = UserSelection.Category, type = UserSelection.Type, difficulty = UserSelection.Difficulty, noOfQuestions= UserSelection.NoofQuestions });
        }
    }
}

Pages/Quiz/QuizMatch.cshtml
@page
@model BrainBox.Pages.Quiz.QuizMatchModel
@{
}


<p style="color:white"><strong>Category :</strong> @Model.Category</p>
<p style="color:white"><strong>Type:</strong> @Model.Type</p>

Pages/Quiz/QuizSelection.cshtml
@page
@model BrainBox.Pages.Quiz.QuizSelectionModel

<div class="text-start" style="margin-top:100px;">
    <h1 class="display-4 bungee-spice-regular">Hi,</h1>
    <h1 class="display-4 bungee-spice-regular">@User.FindFirst("FirstName")!.Value</h1>

    <h1 class="display-4 caveat-pacifico-regular" style="color:snow; font-size:xx-large;">Please select from below options :</h1>
    <form method="post" asp-page-handler="RedirectToPage">
        <div>
            <div>
                <h1 class="caveat-pacifico-regular" style="font-size:xxx-large; margin-top:20px; color:fuchsia;">Category</h1>

                <select class="form-control custom-input mt-3" style="width:25%;" asp-for="UserSelection.Category">
                <option value="any">Any Category</option>
                <option value="9">General Knowledge</option>
                <option value="10">Entertainment: Books</option>
                <option value="11">Entertainment: Film</option>
                <option value="14">Entertainment: Television</option>
                <option value="15">Entertainment: Video Games</option>
                <option value="18">Science: Computers</option>
                <option value="19">Science: Mathematics</option>
                <option value="20">Mythology</option>
                <option value="21">Sports</option>
                <option value="22">Geography</option>
                <option value="23">History</option>
                <option value="26">Celebrities</option>
                <option value="27">Animals</option>
                <option value="29">Entertainment: Comics</option>
                <option value="30">Science: Gadgets</option>
                <option value="32">Entertainment: Cartoon &amp; Animations</option>
            </select>
            </div>
            <div>
                <h1 class="caveat-pacifico-regular" style="font-size:xxx-large; margin-top:20px;  color:deepskyblue;">Difficulty</h1>

                <select class="form-control custom-input mt-3" style="width:25%;" asp-for="UserSelection.Difficulty" autocomplete="username">
                    <option value="any">Any Difficulty</option>
                    <option value="easy">Easy</option>
                    <option value="medium">Medium</option>
                    <option value="hard">Hard</option>
                </select>
            </div>
            <div>
                <h1 class="caveat-pacifico-regular" style="font-size:xxx-large; margin-top:20px;  color:mediumaquamarine;">Type</h1>

                <select class="form-control custom-input mt-3" style="width:25%;" asp-for="UserSelection.Type" autocomplete="username">
                    <option value="any">Any Type</option>
                    <option value="multiple">Multiple Choice</option>
                    <option value="boolean">True / False</option>
                </select>
            </div>

            <div>
                <h1 class="caveat-pacifico-regular" style="font-size:xxx-large; margin-top:20px;  color:violet;">No. of questions</h1>

                <input class="form-control custom-input mt-3" min="10" max="20" value="10" type="number" asp-for="UserSelection.NoofQuestions" style="width:25%;">
            </div>
        </div>

        <button class="btn btn-danger mt-5" type="submit">Start</button>

    </form>
</div>